#! /bin/sh
sxhkd &
#wmname LG3D &
#sudo xboxdrv -D --detach-kernel-driver --silent --dbus disabled &
picom --vsync &
dunst -config $HOME/.config/dunst/dunstrc &
wal -o $HOME/Scripts/Xresources_ln.sh -o $HOME/Scripts/rofi_fixer.sh -o $HOME/Scripts/dunst_ln.sh -o $HOME/Scripts/discord_colors.sh -i $HOME/Wallpapers/9.jpg

polybar main &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         0
bspc config window_gap          6
bspc config top_padding		18

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

setxkbmap pl,ru
setxkbmap -option 'grp:win_space_toggle'
kitty bash -c "neofetch; bash" &

#declaring rules
bspc rule -a discord desktop=^9
bspc rule -a firefox desktop=^2
bspc rule -a Steam desktop=^10

#launching applications
spicetify apply &
discord-canary &
discord-ptb &
steam &
com.valvesoftware.Steam &
flameshot &

betterlockscreen -u $HOME/Wallpapers/7.jpg
